### ISSUE TITLE
Error messages with Kernel 5.8.8

### ISSUE THREAD

**Issue by olifre** [kilobyte/compsize#34] opened 2020-09-10 00:32 UTC
After upgrading from 5.8.5 to 5.8.8, `compsize` does almost always abort with:
```
$ compsize -x /usr/
/usr/portage/distfiles/ndata-0.6.1.zip: Regular extent's header not 53 bytes (0) long?!?
```
on various directories and also on different subvolumes. Is there an upstream kernel change this tool needs to be adapted to?

**Comment by olifre** [comment] 2020-09-10 14:26
Reverting to 5.8.5 makes the issues go away, so I presume this is indeed a kernel change and not sudden file system corruption on my end.

**Comment by telans** [comment] 2020-09-12 04:29
Yeah, can confirm for me too.

**Comment by Forza-tng** [comment] 2020-09-12 10:29
Seems I am hit by this too. :/

**Comment by telans** [comment] 2020-09-12 11:07
I imagine it's because of:

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/fs/btrfs?h=v5.8.8&id=26cf893236fd879d4452403cb96bd84e587254d5

**Comment by olifre** [comment] 2020-09-12 17:24
According to:
https://lore.kernel.org/linux-btrfs/632b888d-a3c3-b085-cdf5-f9bb61017d92@lechevalier.se/
that's also visible in 5.8.6, so we are down to changes between 5.8.5 and 5.8.6.

**Comment by telans** [comment] 2020-09-12 20:05
That patch in that thread touches code the commit changed so I imagine it fixes compsize, but I haven't checked yet.

**Comment by olifre** [comment] 2020-09-12 21:39
I've tested the patch and indeed it fixes `compsize` for me. Another report in the thread also mentions problematic behaviour with `bees` was fixed. 
It's still unclear to me why someone in the thread claimed 5.8.6 was affected, too, but maybe that was just a red herring. 

So in principle, this bug can be closed since it's a kernel bug after all, and a fix is available. I personally would leave it open to catch other reporters encountering the same issue so they do not report a duplicate issue, at least until a kernel containing the fix is out, but of course if the `compsize` maintainers want to close it earlier, feel free to do so.

**Comment by kilobyte** [comment] 2020-09-13 01:40
The patch fixes this for me too, both atop 5.8.8 and 5.9-rc4.

Good idea, let's wait until such kernels pass Linus and GregKH.

**Comment by thorstenhirsch** [comment] 2020-09-13 11:36
I'm also affected. Could you please release a new minor version with this fix so that the arch linux package can be updated? https://www.archlinux.org/packages/extra/x86_64/compsize/

**Comment by telans** [comment] 2020-09-13 11:42
> Could you please release a new minor version with this fix

The fix is a patch for the linux kernel, not compsize

**Comment by thorstenhirsch** [comment] 2020-09-13 12:08
Oh... now I see. The issue was caused by a kernel commit AND fixed by a kernel commit. Sorry, I thought it had to be fixed here.

**Comment by kdave** [comment] 2020-09-14 17:00
The kernel fix is on the way to mainline and it might catch the 5.8.10 release.

**Comment by kilobyte** [comment] 2021-05-16 23:30
Those kernel versions have been long since pushed to distributions, let's close.

**Closed by kilobyte** 2021-05-16 23:30 UTC
